# Copyright (c) 2016-2017 ForgeRock AS. Use of this source code is subject to the
# Common Development and Distribution License (CDDL) that can be found in the LICENSE file
# Default values for openam-install.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

# Registry is optional - and should include the trailing /
registry: docker-public.forgerock.io/
repo: forgerock

openam:
  image: openam
  tag: 14.0.0

pullPolicy: IfNotPresent

# Server base URL *within* the Kubernetes cluster - not the external LB URL.
# No /openam appended here.
serverBase: http://openam:80

# What OpenAM is known by *outside* the cluster - includes context root /openam.
# This is currently not used for the install. See templates/config-map.yaml to understand how the
# load balancer URL is derived. If you want to override the calculated value, uncomment the line below and edit the config-map
# to use this variable
#loadBalancerUrl: "http://openam.example.com:80/openam"

fqdnHostname: openam.example.com
cookieDomain: .example.com
amadmin_pw: password

configStore:
  suffix:  "dc=openam,dc=forgerock,dc=org"
  # This is the first StatefulSet name:
  host: configstore-0.configstore
  port: 389
  dirManager: "cn=Directory Manager"
  adminPort: 4444
  password: password

# If skipImport is true, the basic 00_amster.sh config script will be run, but
# the 01* import of config files will not.
amster:
  image: amster
  tag:  14.0.0
  skipImport: false

# default path to Amster *json files to import.
# The default is the amster directory under the forgeops-init project, but if you have a special config you can modify this
amsterImportPath: /amster-config/forgeops-init/amster

# determines if '--clean true' is used for the import-config. It's ignored if skipImport: true
# suggest this is 'true' if importing a complete configuration
# and set to 'false' if importing partial/incremental configurations
amsterClean: true
