apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
data:
  jvm.options: |
    -Xms512m
    -Xmx512m
    -XX:+UseConcMarkSweepGC
    -XX:CMSInitiatingOccupancyFraction=75
    -XX:+UseCMSInitiatingOccupancyOnly
    -XX:+DisableExplicitGC
    -XX:+AlwaysPreTouch
    -server
    -Xss1m

    # Set to headless, just in case.
    -Djava.awt.headless=true

    # Ensure UTF-8 encoding by default (e.g. filenames).
    -Dfile.encoding=UTF-8

    # Use our provided JNA always versus the system one.
    -Djna.nosys=true

    # Use old-style file permissions on JDK9.
    -Djdk.io.permissionsUseCanonicalPath=true

    # Flags to configure Netty:
    -Dio.netty.noUnsafe=true
    -Dio.netty.noKeySetOptimization=true
    -Dio.netty.recycler.maxCapacityPerThread=0

    # log4j 2:
    -Dlog4j.shutdownHookEnabled=false
    -Dlog4j2.disable.jmx=true
    -Dlog4j.skipJansi=true

    ## Heap dumps:

    # Generate a heap dump when an allocation from the Java heap fails.
    # Heap dumps are created in the working directory of the JVM.
    -XX:+HeapDumpOnOutOfMemoryError
  elasticsearch.yml: |
    cluster.name: "docker-cluster"
    network.host: 0.0.0.0
    http.host: 0.0.0.0
    transport.host: 127.0.0.1

    # Disable security - we run only in the cluster.
    xpack.security.enabled: false

    # minimum_master_nodes need to be explicitly set when bound on a public IP.
    # Set to 1 to allow single node clusters.
    # Details: https://github.com/elastic/elasticsearch/pull/17288
    discovery.zen.minimum_master_nodes: 1

  log4j2.properties: |
    status = error

    appender.console.type = Console
    appender.console.name = console
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = [%d{ISO8601}][%-5p][%-25c{1.}] %marker%m%n

    rootLogger.level = info
    rootLogger.appenderRef.console.ref = console