apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: ClusterIP
  ports:
  - port:  9200
    targetPort: 9200
    protocol: TCP
    name: elasticsearch
  selector:
    app: {{ template "fullname" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: ClusterIP
  ports:
  - port:  5601
    targetPort: 5601
    protocol: TCP
    name: kibana
  selector:
    app: {{ template "fullname" . }}
