# Copyright (c) 2016-2017 ForgeRock AS. Use of this source code is subject to the
# Common Development and Distribution License (CDDL) that can be found in the LICENSE file
# Config map holds the boot.json for this instance.
apiVersion: v1
kind: ConfigMap
metadata:
  name: boot-json
data:
  boot.json: |
   {
     "instance" : "{{ default "http://openam:80/openam" .Values.openamInstance }}",
     "dsameUser" : "cn=dsameuser,ou=DSAME Users,{{ .Values.rootSuffix }}",
     "keystores" : {
       "default" : {
         "keyStorePasswordFile" : "/root/openam/openam/.storepass",
         "keyPasswordFile" : "/root/openam/openam/.keypass",
         "keyStoreType" : "JCEKS",
         "keyStoreFile" : "/root/openam/openam/keystore.jceks"
       }
     },
     "configStoreList" : [ {
       "baseDN" : "{{.Values.rootSuffix }}",
       "dirManagerDN" : "cn=Directory Manager",
       "ldapHost" : "{{ default "opendj-configstore-0.opendj-configstore" .Values.configLdapHost }}",
       "ldapPort" : {{ default 389 .Values.configLdapPort }},
       "ldapProtocol" : "ldap"
     } ]
   }
