apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: openidm
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: openidm
        image: "{{.Values.registry}}{{.Values.repo}}/{{.Values.openidm.image }}:{{ .Values.openidm.tag }}"
        imagePullPolicy: {{ .Values.pullPolicy }}
        env:
        - name: PROJECT_HOME
          value: "/opt/openidm/custom/forgeops-init/{{ .Values.openidmProjectHome }}"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /openidm/info/ping
            port: {{ .Values.service.internalPort }}
            httpHeaders:
            - name: X-OpenIDM-Username
              value: anonymous
            - name: X-OpenIDM-Password
              value: anonymous
            - name: X-OpenIDM-NoSession
              value:  "true"
          initialDelaySeconds: 90
          timeoutSeconds: 5
          periodSeconds: 20
        resources:
{{ toYaml .Values.resources | indent 12 }}
        volumeMounts:
        - name: openidm-secrets
          mountPath: /opt/openidm/secrets
        - name:  forgeops-init
          mountPath: /opt/openidm/custom
      volumes:
      - name: openidm-secrets
        secret:
          secretName: openidm-secrets
      - name: forgeops-init
{{ toYaml .Values.stackConfigSource | indent 8 -}}