# Copyright (c) 2016-2017 ForgeRock AS. Use of this source code is subject to the
# Common Development and Distribution License (CDDL) that can be found in the LICENSE file
#
# Deployment to run the ddclient dynamic dns updater. This is useful for
# for development to provide a dynamic dns name
#
# Copy this to ddclient.yaml, and edit the variables below starting with YOUR_
# Then run  kubectl create -f ddclient.yaml
# Note that passwords in this file should not be checked in to git!
apiVersion: v1
kind: ConfigMap
metadata:
  name: ddclient-config
data:
  ddclient.conf: |
    ## ddclient configuration file
    daemon=600
    # check every 600 seconds
    syslog=yes
    ssl=yes
    # log update msgs to syslog
    mail-failure=YOUR_EMAIL_TO_NOTIFY
    pid=/var/run/ddclient.pid
    # record PID in file.
    ## Detect IP with our CheckIP server
    use=web, web=checkip.dyndns.com/, web-skip='IP Address'
    ## DynDNS username and password here
    cache=/var/tmp/ddclient.cache
    login=DYNDNS_LOGIN
    password=DYNDNS_PASSWORD
    ## Default options
    protocol=dyndns2
    server=members.dyndns.org
    ## Dynamic DNS hosts  to update - csv seperated, no spaces
    DYNDNS_HOSTS
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ddclient
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: ddclient
    spec:
      containers:
      - name: ddclient
        image: digrouz/docker-alp-ddclient:latest
        volumeMounts:
        - name: config
          mountPath: /etc/ddclient
      volumes:
      - name: config
        configMap:
          name: ddclient-config