# Default values for openidm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# optional registry, including trailing /
registry:  docker-public.forgerock.io/
repo: forgerock


pullPolicy: IfNotPresent


replicaCount: 1

image:

service:
  name: openidm
  type: NodePort
  externalPort: 80
  internalPort: 8080

resources:
  limits:
    cpu: 300m
    memory: 1000Mi
  requests:
    cpu: 300m
    memory: 1000Mi

openidm:
  image: openidm
  tag: 5.0.0

# The *relative* path where the conf/ directory is found. This is relative to the root of the forgeops-init volume.
# The default is usually fine.
openidmProjectHome: openidm

# This is used by the ingress controller to route to OpenIDM.
#fqdn: openidm.{{ .Values.cookieDomain }}
cookieDomain: .example.com
